import manifest from "@site/static/img/og/manifest.json";

/**
 * Social cards are generated by `npm run og` (scripts/generate-og-images.mjs)
 * into static/img/og/<locale>/, and listed in manifest.json. Pages without a
 * generated card fall back to the default card in themeConfig.image.
 */
const cards = manifest as Record<string, string[]>;

export function ogSlug(path: string): string {
  const clean = path.replace(/\/+$/, "");
  return clean === "" ? "home" : clean.slice(1).replace(/\//g, "--");
}

/**
 * @param path Page path without the locale's baseUrl, e.g. "/start".
 * @returns Site-relative image path, or undefined when no card exists.
 */
export function ogImageFor(locale: string, path: string): string | undefined {
  const slug = ogSlug(path);
  return cards[locale]?.includes(slug)
    ? `/img/og/${locale}/${slug}.png`
    : undefined;
}
